### ISSUE TITLE
torch.cat(): expected a non-empty list of Tensors

### ISSUE THREAD

**Issue by huanggou666** [kijai/ComfyUI-MochiWrapper#11]
![image](https://github.com/user-attachments/assets/0f6538f2-c3df-4288-8d1d-88b2226e4bf6)

**Comment by huanggou666** [comment]
Problem solved ,These two numbers need to be divisible
![image](https://github.com/user-attachments/assets/c9104320-97f0-4da6-91c8-0381350f171c)

**Comment by steven850** [comment]
@kijai Since the frame count needs to be divisible by the batch size, could you change the step size on the num_frames?
at the moment you cant do a 2 or 3 second video, as all the frame numbers are odd and not even.  have to go all the way to 4 seconds before hitting a divisible number again.

**Comment by kijai** [comment]
The way the VAE works is that it packs 6 images into one latent, it won't work for any other values than 6+1, which is why the step is 6 and minimum is 7.

The decoding frame value is in latent space, so it should be 6 minimum from what I've seen or you're skipping frames. I still don't know the math for choosing optimal value for different frame counts, for example 49 with 6 works near perfect, but 163 with 6 has clear frame skips. The errors earlier were about having higher frame batch size than you had latents in the result, I changed it to adjust to the actual latent count if it's higher in update yesterday so it won't error in those cases.

Whole VAE decoding needs to be better, this is based on the CogVideoX tiled decoding from diffusers, and it wasn't directly applicable as with CogvideoX you can do 2 latents at once perfectly fine, while with mochi you can't, and that makes this a bit hacky solution.
